/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataAccess.InventoryFileReader;
import Model.Car;
import Model.CarType;
import Model.Engine;
import Model.FuelType;
import Model.Interior;
import Model.Trunk;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author msalehan
 */
public class AddCarForm extends javax.swing.JFrame {

    private String sError = "";
    private String[] toyotaModels = {"Corolla", "Camry", "C-HR", "RAV4", "Land Cruiser", "Prius", "Yaris"};
    private String[] lexusModels = {"IS", "RX", "GS", "LS", "LX", "ES", "NX", "RC"};
    private String[] infinitModels = {"Q50", "QX30", "QX80", "Q60", "QX60", "QX70"};
    private String[] acuraModels = {"NSX", "MDX", "TLX", "RDX", "ILX", "RLX"};
    private String[] hyundaiModels = {"Elantra", "Tucson", "Accent", "Santa Fe", "Sonata", "Azera"};
    private String[] nissanModels = {"GT-R", "Frontier", "Juke", "Sentra", "Altima", "Pathfinder", "Maxima"};

    /**
     * Creates new form AddCarForm
     */
    public AddCarForm() {
        initComponents();
        
        for(int i = 1980; i <= 2018; i++)
        {
            jComboBoxYear.addItem(i + "");
        }
        

        for(int i = 0; i < toyotaModels.length; i++)
        {
             jComboBoxModel.addItem(toyotaModels[i]);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCheckBoxSunRoof = new javax.swing.JCheckBox();
        jCheckBoxMoonRoof = new javax.swing.JCheckBox();
        jCheckBoxPanoramicRoof = new javax.swing.JCheckBox();
        jCheckBoxSpareTire = new javax.swing.JCheckBox();
        jCheckBoxTrunkCarpet = new javax.swing.JCheckBox();
        jCheckBoxJack = new javax.swing.JCheckBox();
        jCheckBoxFirstAidKit = new javax.swing.JCheckBox();
        jComboBoxMake = new javax.swing.JComboBox<>();
        jComboBoxModel = new javax.swing.JComboBox<>();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jTextFieldPrice = new javax.swing.JTextField();
        jComboBoxCarType = new javax.swing.JComboBox<>();
        jComboBoxFuelType = new javax.swing.JComboBox<>();
        jcomboBoxNoOfCylinders = new javax.swing.JComboBox<>();
        jTextFieldMPG = new javax.swing.JTextField();
        jTextFieldMiles = new javax.swing.JTextField();
        jTextFieldColor = new javax.swing.JTextField();
        jTextFieldInteriorColor2 = new javax.swing.JTextField();
        jTextFieldInteriorColor1 = new javax.swing.JTextField();
        jTextFieldCapacity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldHorsePower = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Car");

        jLabel1.setText("Make:");

        jLabel2.setText("Interior color 2:");

        jLabel3.setText("Model:");

        jLabel4.setText("Interior color 1:");

        jLabel5.setText("Miles per gallon:");

        jLabel6.setText("Year:");

        jLabel7.setText("Color:");
        jLabel7.setToolTipText("");

        jLabel8.setText("Price:");

        jLabel9.setText("Miles:");

        jLabel10.setText("Type:");

        jLabel11.setText("Fuel Type:");

        jLabel12.setText("No of cylinders:");

        jLabel13.setText("Engine capacity:");

        jLabel14.setText("Horse power:");

        jCheckBoxSunRoof.setText("Sun roof");

        jCheckBoxMoonRoof.setText("Moon roof");

        jCheckBoxPanoramicRoof.setText("Panoramic roof");

        jCheckBoxSpareTire.setText("Spare tire");

        jCheckBoxTrunkCarpet.setText("Trunk carpet");

        jCheckBoxJack.setText("Jack");

        jCheckBoxFirstAidKit.setText("First aid kit");

        jComboBoxMake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Lexus", "Infiniti", "Acura", "Hyndai", "Nissan" }));
        jComboBoxMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMakeActionPerformed(evt);
            }
        });

        jComboBoxModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModelActionPerformed(evt);
            }
        });

        jComboBoxYear.setEditable(true);
        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jComboBoxCarType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "SUV", "CrossOver", "Truck" }));

        jComboBoxFuelType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gas", "Electric", "Hybrid", "Diesel" }));

        jcomboBoxNoOfCylinders.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxCarType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcomboBoxNoOfCylinders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel9)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)))
                                .addGap(25, 25, 25)
                                .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldMiles, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jLabel2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldHorsePower, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldInteriorColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldMPG, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldInteriorColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxSunRoof)
                                    .addComponent(jCheckBoxJack))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxFirstAidKit)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxMoonRoof)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxPanoramicRoof)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxSpareTire)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxTrunkCarpet)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel10)
                                .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jComboBoxFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldMiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jcomboBoxNoOfCylinders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldMPG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHorsePower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldInteriorColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldInteriorColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSunRoof)
                    .addComponent(jCheckBoxMoonRoof)
                    .addComponent(jCheckBoxPanoramicRoof)
                    .addComponent(jCheckBoxSpareTire)
                    .addComponent(jCheckBoxTrunkCarpet))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxJack)
                    .addComponent(jCheckBoxFirstAidKit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainForm formButton;
        try {
            formButton = new MainForm();
             formButton.setVisible(false);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(AddCarForm.class.getName()).log(Level.SEVERE, null, ex);
            
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add the addition of a car, it is extremely recommended that you validate your information
                // TODO add your handling code here:
        InventoryFileReader iReader = new InventoryFileReader();
        ArrayList<Car> cars = iReader.getAllCars();
        
        String make = jComboBoxMake.getSelectedItem() + "";
        String model = jComboBoxModel.getSelectedItem() + "";
        int price = Integer.parseInt(jTextFieldPrice.getText());
        int year = Integer.parseInt(jComboBoxYear.getSelectedItem() + "");
        String color = jTextFieldCapacity.getText() + "";
        CarType carType = CarType.valueOf(jComboBoxCarType.getSelectedItem() + "");
        int miles = 100;
        FuelType fuelType = FuelType.valueOf(jComboBoxFuelType.getSelectedItem() + "");
        int noOfCylinders = Integer.parseInt(jcomboBoxNoOfCylinders.getSelectedItem() + "");
        int capacity = Integer.parseInt(jTextFieldCapacity.getText());
        int horsePower = Integer.parseInt(jTextFieldHorsePower.getText());
        int mpg = Integer.parseInt(jTextFieldMPG.getText());
        String color1 = jTextFieldInteriorColor1.getText();
        String color2 = jTextFieldInteriorColor2.getText();
        boolean sunRoof = false, moonRoof = false, panoramicRoof = false, spareTire= false, trunkCarpet = false, jack = false, firstAidkit = false;
        
        if(jCheckBoxSunRoof.isSelected())
            sunRoof = true;
        if(jCheckBoxMoonRoof.isSelected())
            moonRoof = true;
        if(jCheckBoxPanoramicRoof.isSelected())
            panoramicRoof = true;
        if(jCheckBoxSpareTire.isSelected())
            spareTire = true;
        if(jCheckBoxTrunkCarpet.isSelected())
            trunkCarpet = true;
        if(jCheckBoxJack.isSelected())
            jack = true;
        if(jCheckBoxFirstAidKit.isSelected())
            firstAidkit = true;
                
        
        Car car = new Car(make, year, model, price, color, miles, carType,new Engine(fuelType, noOfCylinders, capacity, horsePower, mpg),
                            new Interior(color1, color2, sunRoof, moonRoof, panoramicRoof), new Trunk(spareTire, firstAidkit, trunkCarpet, jack));
        
        iReader.addCar(cars, car);
        
        JOptionPane.showMessageDialog(this, "Added Vehicle!");

        this.setVisible(false);
        MainForm mForm;
    try {
        mForm = new MainForm();
        mForm.setVisible(false);
    } catch (IOException ex) {
        Logger.getLogger(ViewCarForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModelActionPerformed
        // TODO add your handling code here:
        int index = jComboBoxModel.getSelectedIndex();
        
    }//GEN-LAST:event_jComboBoxModelActionPerformed

    private void jComboBoxMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMakeActionPerformed
        // TODO add your handling code here:
        int index = jComboBoxMake.getSelectedIndex();
        
        jComboBoxModel.removeAllItems();
        
        if(index == 0)
        {
            for(int i = 0; i < toyotaModels.length; i++)
            {
                jComboBoxModel.addItem(toyotaModels[i]);
            }
        }
        else if(index == 1)
        {
            for(int i = 0; i < lexusModels.length; i++)
            {
                jComboBoxModel.addItem(lexusModels[i]);
            }
        }
        else if(index == 2)
        {
            for(int i = 0; i < infinitModels.length; i++)
            {
                jComboBoxModel.addItem(infinitModels[i]);
            }
        }
        else if(index == 3)
        {
            for(int i = 0; i < acuraModels.length; i++)
            {
                jComboBoxModel.addItem(acuraModels[i]);
            }
        }
        else if(index == 4)
        {
            for(int i = 0; i < hyundaiModels.length; i++)
            {
                jComboBoxModel.addItem(hyundaiModels[i]);
            }
        }
        else if(index == 5)
        {
            for(int i = 0; i < nissanModels.length; i++)
            {
                jComboBoxModel.addItem(nissanModels[i]);
            }
        }
    }//GEN-LAST:event_jComboBoxMakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCarForm().setVisible(true);
            }
        });
    }
    
    private boolean isValidComboBox(int selection)
    {
        boolean bResult = false;
        
        if(selection > -1)
        {
            bResult = true;
        }
        else
        {
            addError("You must select one item from each combo box.");
        }
        
        return bResult;
    }
    
    private boolean isValidNumber(String s)
    {
        return false;
    }
    
    private boolean isValidString(String s)
    {
        return false;
    }
    
    private String addError(String s)
    {      
        return sError += s + "\n";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxFirstAidKit;
    private javax.swing.JCheckBox jCheckBoxJack;
    private javax.swing.JCheckBox jCheckBoxMoonRoof;
    private javax.swing.JCheckBox jCheckBoxPanoramicRoof;
    private javax.swing.JCheckBox jCheckBoxSpareTire;
    private javax.swing.JCheckBox jCheckBoxSunRoof;
    private javax.swing.JCheckBox jCheckBoxTrunkCarpet;
    private javax.swing.JComboBox<String> jComboBoxCarType;
    private javax.swing.JComboBox<String> jComboBoxFuelType;
    private javax.swing.JComboBox<String> jComboBoxMake;
    private javax.swing.JComboBox<String> jComboBoxModel;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldCapacity;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldHorsePower;
    private javax.swing.JTextField jTextFieldInteriorColor1;
    private javax.swing.JTextField jTextFieldInteriorColor2;
    private javax.swing.JTextField jTextFieldMPG;
    private javax.swing.JTextField jTextFieldMiles;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JComboBox<String> jcomboBoxNoOfCylinders;
    // End of variables declaration//GEN-END:variables
}
